name: "Build Container"
on:
  push:
    branches:
      - master
    paths:
      - "!README.md"

env:
  VERSION_NUMBER: 4.5

jobs:
  build_image:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Build Container"
        run: docker build . --tag app_image

      - name: "Login to GitHub Packages Docker Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Tag and Push Images"
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}
          docker tag app_image $IMAGE_ID:$VERSION_NUMBER
          docker tag app_image $IMAGE_ID:latest
          docker push $IMAGE_ID:$VERSION_NUMBER
          docker push $IMAGE_ID:latest